spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
  redis:
    host: 127.0.0.1

logging:
  level:
    root: warn
    pers.fjl.server: debug
  file:
    path: log/blog-prod.log
